### ISSUE TITLE
Does not work with Turbopack

### ISSUE THREAD

**Issue by agusterodin** [alex3165/react-mapbox-gl#1035]
When attempting to run my project in Next.js 15.0.3 with Turbopack enabled (dev mode), this package (v5.1.1) causes my application to crash.

```
TypeError: Cannot set property accessToken of [object Module] which has only a getter
    at ReactMapboxGl.componentDidMount (http://localhost:3000/_next/static/chunks/08b5e__pnpm_d9a08c._.js:212:227)
    at commitLayoutEffectOnFiber (http://localhost:3000/_next/static/chunks/486ae_react-dom_cjs_react-dom_development_83ef4e.js:19757:58)
    at commitLayoutMountEffects_complete (http://localhost:3000/_next/static/chunks/486ae_react-dom_cjs_react-dom_development_83ef4e.js:20883:25)
    at commitLayoutEffects_begin (http://localhost:3000/_next/static/chunks/486ae_react-dom_cjs_react-dom_development_83ef4e.js:20872:21)
    at commitLayoutEffects (http://localhost:3000/_next/static/chunks/486ae_react-dom_cjs_react-dom_development_83ef4e.js:20822:13)
    at commitRootImpl (http://localhost:3000/_next/static/chunks/486ae_react-dom_cjs_react-dom_development_83ef4e.js:22611:17)
    at commitRoot (http://localhost:3000/_next/static/chunks/486ae_react-dom_cjs_react-dom_development_83ef4e.js:22501:17)
    at performSyncWorkOnRoot (http://localhost:3000/_next/static/chunks/486ae_react-dom_cjs_react-dom_development_83ef4e.js:22038:13)
    at flushSyncCallbacks (http://localhost:3000/_next/static/chunks/486ae_react-dom_cjs_react-dom_development_83ef4e.js:10480:40)
    at http://localhost:3000/_next/static/chunks/486ae_react-dom_cjs_react-dom_development_83ef4e.js:21666:33
```

**Comment by agusterodin** [comment]
Fixed the issue using `pnpm patch`. I got rid of the lines where access token is set directly on MapboxGL instance and instead pass `accessToken` as an option. The map now works as expected.

react-mapbox-gl@5.1.1.patch
```
diff --git a/CHANGELOG.md b/CHANGELOG.md
deleted file mode 100644
index 0097a510a7c77eee038ae86b12960661f2624b7e..0000000000000000000000000000000000000000
diff --git a/lib-esm/map.js b/lib-esm/map.js
index a475a3614397218bd2fcb5cdc3c1849043faf6c4..6c4993fa9cfbfe27eec0e95b9da665012d7e8999 100644
--- a/lib-esm/map.js
+++ b/lib-esm/map.js
@@ -56,7 +56,6 @@ var ReactMapboxFactory = function (_a) {
             ReactMapboxGl.prototype.componentDidMount = function () {
                 var _this = this;
                 var _a = this.props, style = _a.style, onStyleLoad = _a.onStyleLoad, center = _a.center, pitch = _a.pitch, zoom = _a.zoom, fitBounds = _a.fitBounds, fitBoundsOptions = _a.fitBoundsOptions, bearing = _a.bearing, maxBounds = _a.maxBounds;
-                MapboxGl.accessToken = accessToken;
                 if (apiUrl) {
                     MapboxGl.config.API_URL = apiUrl;
                 }
@@ -64,6 +63,7 @@ var ReactMapboxFactory = function (_a) {
                     throw new Error('zoom need to be an array type of length 1 for reliable update');
                 }
                 var opts = {
+                    accessToken,
                     preserveDrawingBuffer: preserveDrawingBuffer,
                     hash: hash,
                     zoom: zoom[0],
```
