### ISSUE TITLE
running tests with react-mapbox-gl installed

### ISSUE THREAD

**Issue by calocan** [alex3165/react-mapbox-gl#116]
I'm probably doing something obviously wrong here, but whenever react-mapbox-gl is installed I can't run any tests with babel-node. If my test command is:

```
cross-env $NODE_DEBUG_OPTION NODE_PATH='source' babel-node source/test/index.js
```

I get the following error when browserify tries to parse the dist. Is there a way to prevent this error or at least have babel-node ignore the module?

```
/Users/andy/code/rescape_ramble/node_modules/mapbox-gl/dist/mapbox-gl.js:225
"use strict";module.exports=self;
                            ^

ReferenceError: self is not defined
    at Object.112 (/Users/andy/code/rescape_ramble/node_modules/mapbox-gl/dist/js/util/browser/window.js:4:18)
    at s (/Users/andy/code/rescape_ramble/node_modules/mapbox-gl/dist/node_modules/browser-pack/_prelude.js:1:1)
    at /Users/andy/code/rescape_ramble/node_modules/mapbox-gl/dist/node_modules/browser-pack/_prelude.js:1:1
    at Object.110../window (/Users/andy/code/rescape_ramble/node_modules/mapbox-gl/dist/js/util/browser.js:8:16)
    at s (/Users/andy/code/rescape_ramble/node_modules/mapbox-gl/dist/node_modules/browser-pack/_prelude.js:1:1)
    at /Users/andy/code/rescape_ramble/node_modules/mapbox-gl/dist/node_modules/browser-pack/_prelude.js:1:1
    at Object.24.../package.json (/Users/andy/code/rescape_ramble/node_modules/mapbox-gl/dist/js/mapbox-gl.js:3:17)
    at s (/Users/andy/code/rescape_ramble/node_modules/mapbox-gl/dist/node_modules/browser-pack/_prelude.js:1:1)
    at e (/Users/andy/code/rescape_ramble/node_modules/mapbox-gl/dist/node_modules/browser-pack/_prelude.js:1:1)
    at /Users/andy/code/rescape_ramble/node_modules/mapbox-gl/dist/node_modules/browser-pack/_prelude.js:1:1

```

**Comment by alex3165** [comment]
Once https://github.com/alex3165/react-mapbox-gl/pull/114 will be merged it should be different, can you test your issue against this branch ?
