### ISSUE TITLE
AWS NodeJS Deploy Breaking

### ISSUE THREAD

**Issue by iop280** [alex3165/react-mapbox-gl#185]
Ever since updating my package from 1.5.2, deployment appear to be breaking. I believe it has something to do with the mapbox-gl dependency on react-mapbox-gl. I've attached the logs below:

```
157638 verbose stack Error: mapbox-gl@0.34.0 postinstall: `cd src/style-spec && yarn || npm install`
157638 verbose stack Exit status 243
157638 verbose stack     at EventEmitter.<anonymous> (/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
157638 verbose stack     at emitTwo (events.js:106:13)
157638 verbose stack     at EventEmitter.emit (events.js:191:7)
157638 verbose stack     at ChildProcess.<anonymous> (/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:40:14)
157638 verbose stack     at emitTwo (events.js:106:13)
157638 verbose stack     at ChildProcess.emit (events.js:191:7)
157638 verbose stack     at maybeClose (internal/child_process.js:877:16)
157638 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
157639 verbose pkgid mapbox-gl@0.34.0
157640 verbose cwd /tmp/deployment/application
157641 error Linux 4.4.41-36.55.amzn1.x86_64
157642 error argv "/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/npm" "--production" "install"
157643 error node v6.9.1
157644 error npm  v3.10.8
157645 error code ELIFECYCLE
157646 error mapbox-gl@0.34.0 postinstall: `cd src/style-spec && yarn || npm install`
157646 error Exit status 243
157647 error Failed at the mapbox-gl@0.34.0 postinstall script 'cd src/style-spec && yarn || npm install'.
157647 error Make sure you have the latest version of node.js and npm installed.
157647 error If you do, this is most likely a problem with the mapbox-gl package,
157647 error not with npm itself.
157647 error Tell the author that this fails on your system:
157647 error     cd src/style-spec && yarn || npm install
157647 error You can get information on how to open an issue for this project with:
157647 error     npm bugs mapbox-gl
157647 error Or if that isn't available, you can get their info via:
157647 error     npm owner ls mapbox-gl
157647 error There is likely additional logging output above.
157648 verbose exit [ 1, true ]
```

Would love any comments regarding this.

**Comment by mariokam** [comment]
Exactly the same error, got today. Please Mapbox help!

**Comment by iop280** [comment]
Ah I realized that it's because my AWS instance did not have enough memory to complete the npm install. Upgrading the instance to a higher memory one solved it.
