### ISSUE TITLE
Server side rendering bug

### ISSUE THREAD

**Issue by stereobooster** [alex3165/react-mapbox-gl#240]
I'm using CRA 1.0.7 and react-snapshot 1.0.4. Getting this:

```
Pushstate server started on port 2999

🕷   Starting crawling http://localhost:2999
Error: Uncaught [TypeError: o.URL.createObjectURL is not a function]
    at reportException (/map-react/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
    at processJavaScript (/map-react/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)
    at HTMLScriptElementImpl._eval (/map-react/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
    at /map-react/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
    at Object.check (/map-react/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:89:11)
    at /map-react/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:108:12
    at wrappedEnqueued (/map-react/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
    at Request.request [as _callback] (/map-react/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:203:9)
    at Request.self.callback (/map-react/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13) TypeError: o.URL.createObjectURL is not a function
    at Object.o.196.../../source/worker (http://localhost:2999/static/js/main.e1936e75.js:1:488554)
    at i (http://localhost:2999/static/js/main.e1936e75.js:1:49924)
    at http://localhost:2999/static/js/main.e1936e75.js:1:49975
    at Object.o.217.../ (http://localhost:2999/static/js/main.e1936e75.js:1:515610)
    at i (http://localhost:2999/static/js/main.e1936e75.js:1:49924)
    at http://localhost:2999/static/js/main.e1936e75.js:1:49975
    at Object.o.205../worker_pool (http://localhost:2999/static/js/main.e1936e75.js:1:494710)
    at i (http://localhost:2999/static/js/main.e1936e75.js:1:49924)
    at http://localhost:2999/static/js/main.e1936e75.js:1:49975
    at Object.o.149.../render/line_atlas (http://localhost:2999/static/js/main.e1936e75.js:1:369730)
✏️   Saving / as /index.html
🕸   Finished crawling.
```

Seems to be this [line](https://github.com/substack/webworkify/blob/master/index.js#L77). No evidence. Will try to craft example/nail down reason.

**Comment by stereobooster** [comment]
This is because jsdom miss some polyfils https://github.com/tmpvar/jsdom/issues/1721

**Comment by stereobooster** [comment]
Workaround https://github.com/geelen/react-snapshot/pull/34
