### ISSUE TITLE
Error rendering component in puppeteer

### ISSUE THREAD

**Issue by stereobooster** [alex3165/react-mapbox-gl#417]
At first I thought it is an error of mapbox-gl https://github.com/mapbox/mapbox-gl-js/issues/3437. But than I tried vanila mapbox-gl and it works fine.

```
Error: TypeError: Cannot read property 'resize' of undefined
    at resize (../node_modules/mapbox-gl/dist/mapbox-gl.js:398:5239)
    at resize (../node_modules/mapbox-gl/dist/mapbox-gl.js:398:2910)
    at n.componentDidMount (../node_modules/react-mapbox-gl/lib/map.js:132:0)
    at componentDidMount (../node_modules/react-dom/cjs/react-dom.production.min.js:169:71)
    at Nh (../node_modules/react-dom/cjs/react-dom.production.min.js:180:195)
    at c (../node_modules/react-dom/cjs/react-dom.production.min.js:183:347)
    at k (../node_modules/react-dom/cjs/react-dom.production.min.js:184:366)
    at p (../node_modules/react-dom/cjs/react-dom.production.min.js:188:389)
    at y (../node_modules/react-dom/cjs/react-dom.production.min.js:187:415)
    at c (../node_modules/react-dom/cjs/react-dom.production.min.js:248:42)
```

I will try to get more information later.

**Comment by stereobooster** [comment]
I created demo project https://github.com/stereobooster/mapbox-prerender

**Comment by stereobooster** [comment]
This is mapbox-gl error, I was able to reproduce it with pure mapbox-gl. https://github.com/mapbox/mapbox-gl-js/issues/5460
