### ISSUE TITLE
"uncaught" error wont load css

### ISSUE THREAD

**Issue by Aid19801** [alex3165/react-mapbox-gl#813]
can't seem to get this to load into an electron react app

```
vm.js:86 Uncaught /Users/me/Documents/tpr-electron/app/node_modules/mapbox-gl/dist/mapbox-gl.css:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { .mapboxgl-map{font:12px/20px Helvetica Neue,Arial,Helvetica,sans-serif;overflow:hidden;position:relative;-webkit-tap-highlight-color:rgba(0,0,0,0);text-align:left}.mapboxgl-map:-webkit-full-screen{width:100%;height:100%}.mapboxgl-canary{background-color:salmon}.mapboxgl-canvas-container.mapboxgl-interactive,.mapboxgl-ctrl-group button.mapboxgl-ctrl-compass{cursor:-webkit-grab;cursor:-moz-grab;cursor:grab;-moz-user-select:none;-webkit-user-select:none;-ms-user-select:none;user-select:none}.mapboxgl-canvas-container.mapboxgl-interactive.mapboxgl-track-pointer{cursor:pointer}.mapboxgl-canvas-container.mapboxgl-interactive:active,.mapboxgl-ctrl-group button.mapboxgl-ctrl-compass:active{cursor:-webkit-grabbing;cursor:-moz-grabbing;cursor:grabbing}.mapboxgl-canvas-conta

SyntaxError: Unexpected token '.'
    at new Script (vm.js:86:7)
    at createScript (vm.js:268:10)
    at Object.runInThisContext (vm.js:316:10)
    at Module._compile (internal/modules/cjs/loader.js:805:26)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
```
what am i doing wrong here?>

**Comment by mklopets** [comment]
What are you doing to get this error? Importing the CSS manually in your code? Unclear from the issue...

**Comment by Aid19801** [comment]
@mklopets it was a webpack css-loader issue in the end. Did a few tweaks to my config and it worked fine.
Sorry to bother you. 👍

**Comment by mklopets** [comment]
@Aid19801 glad you got it sorted.
