### ISSUE TITLE
npm run build doesn't seem to work for the examples

### ISSUE THREAD

**Issue by calocan** [alex3165/react-mapbox-gl#88]
Following the instructions of cloning, npm install, and then running npm run build fails on lint:

Error: /Users/andy/code/rescape_ramble/react-mapbox-gl/.eslintrc:
        Configuration for rule "react/jsx-uses-react" is invalid:
        Value "error" is the wrong type.

    at validateRuleOptions (/usr/local/lib/node_modules/eslint/lib/config/config-validator.js:102:15)
    at /usr/local/lib/node_modules/eslint/lib/config/config-validator.js:148:13
    at Array.forEach (native)
    at Object.validate (/usr/local/lib/node_modules/eslint/lib/config/config-validator.js:147:35)
    at Object.load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:390:19)
    at loadConfig (/usr/local/lib/node_modules/eslint/lib/config.js:74:33)
    at getLocalConfig (/usr/local/lib/node_modules/eslint/lib/config.js:177:23)
    at Config.getConfig (/usr/local/lib/node_modules/eslint/lib/config.js:272:22)
    at processText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:203:27)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:270:18)

**Comment by philpl** [comment]
I've just tested the build process after doing a clean install (`rm -rf node_modules; npm i`), and it seems to pass the linting correctly. Are you sure you have the correct version of eslint and eslint-plugin-react installed? An `npm ls` of both eslint and the plugin should yield:

```
eslint@3.12.2
eslint-plugin-react@6.8.0
```

**Comment by calocan** [comment]
Thanks, that explained it.
